"""
Ralph Engine 数据模型

导出所有数据模型类和枚举类型。
"""

# 枚举类型
from .enums import (
    ACPSessionStatus,
    Architecture,
    BuildTool,
    CodeFormatter,
    ContainerStatus,
    DatabaseType,
    DependencyManager,
    EngineType,
    ErrorCategory,
    EventType,
    FrameworkType,
    HealthStatus,
    HookType,
    MigrationTool,
    NetworkMode,
    ProjectType,
    RestartPolicy,
    StrategyType,
    TaskStatus,
    TaskType,
    TestRunner,
    VirtualEnvType,
)

# 常量
from . import constants

# 任务相关模型
from .task import (
    LogEntry,
    Task,
    TaskConfig,
    TaskGraph,
    TaskInfo,
    TaskResult,
)

# 配置相关模型
from .config import (
    BackendConfig,
    Configuration,
    DatabaseConfig,
    DockerConfig,
    EngineConfig,
    FrontendConfig,
    ProjectConfig,
    SystemSettings,
    ValidationResult,
)

# 执行相关模型
from .execution import (
    BranchStatus,
    BuildResult,
    ContextStats,
    ErrorInfo,
    ExecutionResult,
    GitCommit,
    ResourceUsage,
    SecurityViolation,
    TestResult,
)

# 钩子相关模型
from .hook import (
    HookConfig,
    HookContext,
    HookExecutionRecord,
    HookFunction,
    HookResult,
)

# 前端相关模型
from .frontend import (
    BrowserTestResult,
    BrowserType,
    CoverageReport,
    DevServerInfo,
    E2ETestResult,
    FailedE2ETest,
    FailedTestDetail,
    FileCoverage,
    FrontendProjectInfo,
    PackageJsonInfo,
    PlaywrightConfig,
    Screenshot,
    ScreenshotMode,
    TestResult as FrontendTestResult,
    TraceFile,
    TraceMode,
    VideoFile,
    VideoMode,
    ViteConfig,
    VitestConfig,
    VueComponentInfo,
)

# 后端相关模型
from .backend import (
    AssertionInfo,
    BackendError,
    BlackConfig,
    DependencyInfo,
    ErrorParseResult,
    FailedPytestCase,
    FormatResult,
    GoBuildError,
    GoBuildResult,
    GoError,
    GoFailedTest,
    GoProjectInfo,
    GoTestResult,
    IsortConfig,
    MakeResult,
    MakeTarget,
    PipfileInfo,
    PyprojectInfo,
    PythonEnvironmentInfo,
    PythonError,
    PythonProjectInfo,
    PytestConfig,
    PytestResult,
    RequirementsInfo,
    RuffConfig,
)

# 数据库相关模型
from .database import (
    ConnectionInfo,
    ConnectionStatus,
    DatabaseConfig,
    DatabaseError,
    MigrationError,
    MigrationResult,
    PostgreSQLConfig,
    QueryResult,
    RedisConfig,
    TestDatabase,
)

# ACP 相关模型
from .acp import (
    ACPAuditLog,
    ACPBuildResult,
    ACPError,
    ACPExecutionResult,
    ACPGitResult,
    ACPPerformanceMetrics,
    ACPResourceUsage,
    ACPResult,
    ACPSecurityPolicy,
    ACPSession,
    ACPSessionConfig,
    ACPSessionInfo,
    ACPSessionStatus,
    CacheConfig,
    GitAuth,
    LayerInfo,
    LogEntry as ACPLogEntry,
    LogFilter,
    NetworkPolicy,
    ProxyConfig,
    ResourceLimits,
)

__all__ = [
    # 枚举类型
    "ACPSessionStatus",
    "Architecture",
    "BuildTool",
    "CodeFormatter",
    "ContainerStatus",
    "DatabaseType",
    "DependencyManager",
    "EngineType",
    "ErrorCategory",
    "EventType",
    "FrameworkType",
    "HealthStatus",
    "HookType",
    "MigrationTool",
    "NetworkMode",
    "ProjectType",
    "RestartPolicy",
    "StrategyType",
    "TaskStatus",
    "TaskType",
    "TestRunner",
    "VirtualEnvType",
    # 常量模块
    "constants",
    # 任务相关
    "LogEntry",
    "Task",
    "TaskConfig",
    "TaskGraph",
    "TaskInfo",
    "TaskResult",
    # 配置相关
    "BackendConfig",
    "Configuration",
    "DatabaseConfig",
    "DockerConfig",
    "EngineConfig",
    "FrontendConfig",
    "ProjectConfig",
    "SystemSettings",
    "ValidationResult",
    # 执行相关
    "BranchStatus",
    "BuildResult",
    "ContextStats",
    "ErrorInfo",
    "ExecutionResult",
    "GitCommit",
    "ResourceUsage",
    "SecurityViolation",
    "TestResult",
    # 钩子相关
    "HookConfig",
    "HookContext",
    "HookExecutionRecord",
    "HookFunction",
    "HookResult",
    # 前端相关
    "BrowserTestResult",
    "BrowserType",
    "CoverageReport",
    "DevServerInfo",
    "E2ETestResult",
    "FailedE2ETest",
    "FailedTestDetail",
    "FileCoverage",
    "FrontendProjectInfo",
    "FrontendTestResult",
    "PackageJsonInfo",
    "PlaywrightConfig",
    "Screenshot",
    "ScreenshotMode",
    "TraceFile",
    "TraceMode",
    "VideoFile",
    "VideoMode",
    "ViteConfig",
    "VitestConfig",
    "VueComponentInfo",
    # 后端相关
    "AssertionInfo",
    "BackendError",
    "BlackConfig",
    "DependencyInfo",
    "ErrorParseResult",
    "FailedPytestCase",
    "FormatResult",
    "GoBuildError",
    "GoBuildResult",
    "GoError",
    "GoFailedTest",
    "GoProjectInfo",
    "GoTestResult",
    "IsortConfig",
    "MakeResult",
    "MakeTarget",
    "PipfileInfo",
    "PyprojectInfo",
    "PythonEnvironmentInfo",
    "PythonError",
    "PythonProjectInfo",
    "PytestConfig",
    "PytestResult",
    "RequirementsInfo",
    "RuffConfig",
    # 数据库相关
    "ConnectionInfo",
    "ConnectionStatus",
    "DatabaseConfig",
    "DatabaseError",
    "MigrationError",
    "MigrationResult",
    "PostgreSQLConfig",
    "QueryResult",
    "RedisConfig",
    "TestDatabase",
    # ACP 相关
    "ACPAuditLog",
    "ACPBuildResult",
    "ACPError",
    "ACPExecutionResult",
    "ACPGitResult",
    "ACPLogEntry",
    "ACPPerformanceMetrics",
    "ACPResourceUsage",
    "ACPResult",
    "ACPSecurityPolicy",
    "ACPSession",
    "ACPSessionConfig",
    "ACPSessionInfo",
    "ACPSessionStatus",
    "CacheConfig",
    "GitAuth",
    "LayerInfo",
    "LogFilter",
    "NetworkPolicy",
    "ProxyConfig",
    "ResourceLimits",
]
